conf_Feira/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feira.urls')),
    path('', include('grafico.urls')),
    path('', include('usuarios.urls')),
    # path('', include('feira2.urls')),
]

feira/urls.py
from django.urls import path
from .views import BancaView, LeituraView
from .views import LeituraCreate, BancaCreate
from .views import LeituraList, BancaList
from .views import LeituraUpdate, BancaUpdate
from .views import HTMX
from .views import ContaCreate, ContaUpdate, ControleView

urlpatterns = [    
    path('banca/', BancaView.as_view(), name="banca" ),
    path('leitura/',LeituraView.as_view(), name='leitura'),
    path('controle/', ControleView.as_view(), name='controle'),
    
    path('criar/leitura/',LeituraCreate.as_view(), name='criar_leitura'),
    path('criar/banca/',BancaCreate.as_view(), name='criar_banca'),

    path('listar/leitura/',LeituraList.as_view(), name='listar_leitura'),
    path('listar/banca/',BancaList.as_view(), name='listar_banca'),

    path('atualizar/leitura/<int:pk>',LeituraUpdate.as_view(), name='atualizar_leitura'),
    path('atualizar/banca/<int:pk>',BancaUpdate.as_view(), name='atualizar_banca'),
    path("htmx/", HTMX.as_view(), name="htmx"),
    # Conta #
    path("conta/create/", ContaCreate.as_view(), name="conta-create"),
    path("conta/update/<int:pk>", ContaUpdate.as_view(), name="conta-update"),
]

feira/models.py
from django.db import models

# Create your models here.



class Bancas(models.Model):
    numero = models.IntegerField(unique=True, verbose_name="Número")
    qtd = models.IntegerField(default=1)
    obs = models.CharField(max_length=50,null=True, blank=True)
    def __str__(self):
        return f"{self.qtd} - {self.numero} ({self.obs})"
    class Meta:
        ordering = ['numero']

class ContaTotal(models.Model):
    conta = models.FloatField("Conta total", max_length=10)
    kwh = models.FloatField("Kw/h", max_length=5, null=True, blank=True)
    taxaIlum = models.FloatField("Tx iluminação Pública", max_length=5)
    corredor = models.FloatField("Iluminação dos Corredores", max_length=5)
    def __str__(self):
        return f"Valor Total: R$  {self.conta:.2f} Taxa Iluminação: R$ {self.taxaIlum:.2f} Corredor: R$: {self.corredor:.2f}"

class Leitura(models.Model):
    anterior = models.IntegerField(verbose_name='Leitura Anterior')
    atual = models.IntegerField(verbose_name='Leitura Atual')
    data = models.DateTimeField(auto_created=True, auto_now=True)
    banca = models.ForeignKey("Bancas" ,on_delete=models.PROTECT, related_query_name='bancas')
    
    def __str__(self):
        return f"{self.banca.qtd}-Banca: ({self.banca.numero}) - ({self.anterior}-{self.atual}) = [ {self.atual - self.anterior}  Kwh ] R$ {(((self.atual - self.anterior) * 0.75))}- Taxa Iluminação ({self.banca.qtd * 7.50 :.2f})- Area comum ({self.banca.qtd * 8.50}) Total = {((self.atual - self.anterior) * 0.75) + (self.banca.qtd * 7.50) + (self.banca.qtd * 8.50 ):.2f} )"
    class Meta:
        ordering = ['banca']

feira/forms.py
from django import forms
from .models import Bancas, Leitura

class BancasForms(forms.ModelForm):
    class Meta:
        model = Bancas
        fields = ['qtd', 'numero']



class LeituraForms(forms.ModelForm):
    class Meta:
        model = Leitura
        fields = '__all__'
        

feira/views.py
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from .models import Bancas, Leitura, ContaTotal
from django.urls import reverse_lazy

# Create your views here.

################# TemplateView #########################################

class BancaView(TemplateView):
    model = Bancas
    template_name = 'feira/index.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["titulo"] = "Bancas"
        return context

class LeituraView(TemplateView):
    model = Leitura
    template_name = 'feira/index.html'
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["titulo"] = "Leituras"

        return context


################# CreateView #########################################

class BancaCreate(CreateView):
    model = Bancas
    fields = '__all__'
    template_name = 'feira/form.html'
    success_url = reverse_lazy('leitura')

class LeituraCreate(CreateView):
    model = Leitura
    fields = '__all__'
    template_name = 'feira/form.html'
    success_url = reverse_lazy('leitura')

class ContaCreate(CreateView):
    model = ContaTotal
    fields = '__all__'
    template_name = 'feira/form.html'
    success_url = reverse_lazy('leitura')


############ ListView ################################################

class BancaList(ListView):
    model = Bancas
    queryset = Bancas.objects.all()
    template_name = 'feira/bancas_list.html'    

class LeituraList(ListView):
    model = Leitura
    queryset = Leitura.objects.all()
    template_name = 'feira/leitura_list.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        conta = ContaTotal.objects.all()
        context['conta'] = conta        
        return context
    
    
    

############# UpdateView ########################################

class BancaUpdate(UpdateView):
    model = Bancas
    fields = '__all__'
    template_name = 'feira/form.html'
    success_url = reverse_lazy('leitura')

class LeituraUpdate(UpdateView):
    model = Leitura
    fields = '__all__'
    template_name = 'feira/form.html'
    success_url = reverse_lazy('leitura')

class ContaUpdate(UpdateView):
    model = ContaTotal
    fields = '__all__'
    template_name = 'feira/form.html'
    success_url = reverse_lazy('leitura')

class HTMX(TemplateView):
    template_name = "feira/htmx_teste.html"
    

class ControleView(ListView):
    model = Leitura
    queryset = Leitura.objects.all()
    template_name = 'feira/Controle.html'

feira/templates/feira/Controle.html
{% extends 'feira/modelo.html' %}
{% load static %}
{% block titulo %}

{% endblock %}
{% block conteudo %}
<div class="container col-8 auto">
<table class="table table-striped text-center ">    
    <thead>
      <tr>
        <th >Qtd</th>
        <th >Banca</th>
        <th >Leitura anterior (Kw/h) </th>
        <th >Leitura atual (Kw/h) </th>
        <!-- <th >Data da Leitura</th> -->
        <!-- <th >Consumo em Kw/h</th>
        <th >Total a pagar</th>
        <th >Editar </th> -->
      </tr>
    </thead>
    {% for item in object_list %}
    <tbody >      
      <tr > 
        <td class="qtd">{{ item.banca.qtd }}</td>       
        <td>{{ item.banca.numero }}</td>
        <td class="ant">{{ item.atual }}</td>        
        <td class="atual"><input type="text" name="atualizar" id=""></td>
        <!-- <td class="atual"><input type="text" name="data" id=""></td>
        <td class="total"></td> -->
      </tr>      
    </tbody>
    {% endfor %}    
</table>
</div>  
{% endblock %}

feira/templates/feira/bancas_list.html
{% extends 'feira/modelo.html' %}
{% load static %}

{% block title %}
    <title>Bancas</title>
{% endblock %}

{% block titulo %}
    <h1 class="text-danger">Bancas</h1>
{% endblock %}

{% block conteudo %}
    <div class="container">
    <table class="table">        
        <thead class="thead-dark">
            <tr>        
                <div class="input-group mb-3">
                    {% for banca in object_list %}
                    {% if banca.qtd == 1 %}
                        <th class="input-group mb-3" scope="col"><input class="custom-control-input" type="checkbox" > {{ banca.qtd }} - Banca N: {{ banca.numero }} 
                    {% else %}
                        <th class="input-group mb-3 " scope="col"><input type="checkbox"> {{ banca.qtd }} - Banca N: {{ banca.numero }}/{{ banca.obs }}</th>
                </div>                
                    {% endif %}                
            </tr>
        </thead>
                    {% endfor %}
    </table>
</div>
{% endblock %}
{% block rodape %}
    <p class="text-center">Desenvolvido por: <strong>FPS_Neto</strong></p>
{% endblock %}
{% block script %}
        <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
        <script>
            function addClasse(){
                $(this).click(()=>{
                    $('checkbox').toggleClass('checked')
                })
            }
        </script>        
{% endblock %}

feira/templates/feira/form.html
{% extends 'feira/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
    <title>Formulario</title>
{% endblock %}

{% block titulo %}
    <div class="container col-4 auto">
        <h1 class="text-danger">Bem vindo, {{ request.user | title }}</h1>
    </div>
{% endblock %}

{% block conteudo %}
    <div class="container col-6 auto">
        <!--<h3 >alguma coisa aqui</h3>-->
            <!--<div class="col-6 auto">-->
                <form id="meu_form" action="" method="post" class="container">            
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-success sm " type="submit">Confirmar</button>
                    <a class="btn btn-warning sm" href="{% url 'listar_leitura' %}">Voltar</a>
                </form>
            {% comment %} </div> {% endcomment %}
    </div>
{% endblock %}

{% block rodape %}
    <p class="text-center">Desenvolvido por: <strong>FPS_Neto</strong></p>
{% endblock %}
{% block scripts %}
<script id="update" src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'js/atualiza.js' %}"> </script>
<script>
    $("#id_banca").attr('disabled', true);
</script>

{% endblock scripts %}

feira/templates/feira/htmx_teste.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.8.2" integrity="sha384-+8ISc/waZcRdXCLxVgbsLzay31nCdyZXQxnsUy++HJzJliTzxKWr0m1cIEMyUzQu" crossorigin="anonymous"></script>
    <title>Testanto HTMX</title>
</head>
<body>
    <h1>Meu primeiro teste com HTMX</h1>
    <button hx-get="/listar/leitura/"  hx-trigger="click" hx-target="#meu_p" >
        Click Me!
        </button>
         


<h2>Outro exemplo</h2>
<input type="text" name="q" hx-get="/leitura" hx-trigger="click" hx-select="#algo" hx-target="#search-results" placeholder="Search...">
<div id="search-results"></div>
<h3>teste 3</h3>
<button hx-get="/leitura" hx-select="#algo" hx-trigger="click" hx-target="#meu_p" hx-swap="outerHTML" class="btn btn-danger">
    Click Me!
</button>
<p id="pdf" class="nav-link">meu_pdf</p> 
<p id="meu_p"></p> 
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script> 
<script>
    $("#pdf").click(()=>{
        window.print();
    })

</script> 
</body>
</html>

feira/templates/feira/index.html
{% extends 'feira/modelo.html' %}
{% load static %}

{% block title %}
    <title>{{ titulo }}</title>
{% endblock %}


{% block titulo %}
    <h1 class="text-danger">Bem vindo, {{ request.user }}</h1>
{% endblock %}

{% block conteudo %}
    <h3 id="algo">alguma coisa aqui - {{ titulo }}</h3>
{% endblock %}

{% block rodape %}
    <p>Desenvolvido por: <strong>FPS_Neto</strong></p>
{% endblock %}

    

feira/templates/feira/leitura_list.html
{% extends 'feira/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
    <title>leituras</title>
{% endblock %}

{% block titulo %}
  <h1 class="text-danger text-center">estou aqui</h1>
{% endblock %}

{% block conteudo %}
  <div class="container">
    <nav class="nav col-10 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">        
    <table class="table table-striped">    
      <thead>
            <tr>
                <th scope="col">Qtd</th>
                <th scope="col">Banca</th>
                <th scope="col">Anterior</th>
                <th scope="col">Atual</th>
                <th scope="col">Kw/h</th>
                <th scope="col">subtotal</th>
                <th scope="col">Iluminação P.</th>
                <th scope="col">Area Comum</th>
                <th scope="col">Unitário</th>
                <th scope="col">Editar </th>
            </tr>
          </thead>    
    </nav>
      <tbody> 
        {% for item in object_list %}     
          <tr > 
              <td class="qtd">{{ item.banca.qtd  }}</td>       
              <td>{{ item.banca.numero  }}</td>
              <td class="ant">{{ item.anterior  }}</td>        
              <td class="atual">{{ item.atual  }}</td>
              {% for c in conta %}
              
              <td class="soma"></td>
              <td class="subtotal"></td>
              <td class="il-p">{{ c.taxaIlum }}</td>
              <td class="comum">{{ c.corredor }}</td>
              <td class="total"></td>
              <td class="editar-excluir btn btn-info sm ">
                <a href="{% url 'atualizar_leitura' item.pk %}" class="btn btn-warning " title="Editar">E</a> 
              </td>
              {% endfor %}
          </tr> 
        {% endfor %}     
      </tbody>        
    </table>
  </div>
  <p class="TotalSoma"><b>Total Arecadado: </b></p>
{% endblock %}

{% block rodape %}
  <p>Desenvolvido por: <strong>FPS_Neto</strong></p>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'js/feira_leitura_list_soma.js' %}"></script> 
<script src="{% static 'js/feira_leitura_list_total.js' %}"></script>
{% endblock %}

feira/templates/feira/modelo.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.8.2" integrity="sha384-+8ISc/waZcRdXCLxVgbsLzay31nCdyZXQxnsUy++HJzJliTzxKWr0m1cIEMyUzQu" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}
      <title>Modelo</title>
    {% endblock %}
</head>
<body>    
  {% if request.user.is_authenticated %}
  <div class="container">
  <header class="p-3 text-bg-dark">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'listar_leitura' %}" class="nav-link px-2 text-secondary">Leituras</a></li>
          <li><a href="{% url 'controle' %}" class="nav-link px-2 text-white">Controle</a></li>
          <li><a href="{% url 'listar_banca' %}" class="nav-link px-2 text-white">Bancas</a></li>
          <li><a href="{% url 'conta-update' 1 %}" class="nav-link px-2 text-white">Conta</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">{{ request.user | title }}</button>
          <a href="{% url 'logout' %}" class="btn btn-warning">Sign-up</a>
        </div>
      </div>
    </header>
    </div>
  {% endif %}
    {% block titulo %}
        <h1 class="text-success container">Pagina Modelo</h1>
    {% endblock %}
    {% block conteudo %}
    <div class="container">
        <h3>alguma coisa aqui</h3>
    {% endblock %}
    </div>
    {% block rodape %}
        <p>Desenvolvido por: <strong>FPS_Neto</strong></p>
    {% endblock %}

    {% block scripts %}
      <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>        
    {% endblock %}
    </div>
</body>
</html>