conf_Feira/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feira.urls')),
    path('', include('grafico.urls')),
    path('', include('usuarios.urls')),
    # path('', include('feira2.urls')),
]

feira/urls.py
from django.urls import path
from .views import BancaView, LeituraView
from .views import LeituraCreate, BancaCreate
from .views import LeituraList, BancaList
from .views import LeituraUpdate, BancaUpdate
from .views import HTMX
from .views import ContaCreate, ContaUpdate, ControleView

urlpatterns = [    
    path('banca/', BancaView.as_view(), name="banca" ),
    path('leitura/',LeituraView.as_view(), name='leitura'),
    path('controle/', ControleView.as_view(), name='controle'),
    
    path('criar/leitura/',LeituraCreate.as_view(), name='criar_leitura'),
    path('criar/banca/',BancaCreate.as_view(), name='criar_banca'),

    path('listar/leitura/',LeituraList.as_view(), name='listar_leitura'),
    path('listar/banca/',BancaList.as_view(), name='listar_banca'),

    path('atualizar/leitura/<int:pk>',LeituraUpdate.as_view(), name='atualizar_leitura'),
    path('atualizar/banca/<int:pk>',BancaUpdate.as_view(), name='atualizar_banca'),
    path("htmx/", HTMX.as_view(), name="htmx"),
    # Conta #
    path("conta/create/", ContaCreate.as_view(), name="conta-create"),
    path("conta/update/<int:pk>", ContaUpdate.as_view(), name="conta-update"),
]

feira2/urls.py
from django.urls import path
from .views import  ControleView, Leitura2View, Leitura2Update

urlpatterns = [ 
       
    path('controle/', ControleView.as_view(), name='controle'),
    path('leitura/listar', Leitura2View.as_view(), name='leitura-lista'),
    path('leitura/atualizar/<int:pk>/', Leitura2Update.as_view(), name='leitura-atualizar'),


    

]

feira/models.py
from django.db import models

# Create your models here.



class Bancas(models.Model):
    numero = models.IntegerField(unique=True, verbose_name="Número")
    qtd = models.IntegerField(default=1)
    obs = models.CharField(max_length=50,null=True, blank=True)
    def __str__(self):
        return f"{self.qtd} - {self.numero} ({self.obs})"
    class Meta:
        ordering = ['numero']

class ContaTotal(models.Model):
    conta = models.FloatField("Conta total", max_length=10)
    kwh = models.FloatField("Kw/h", max_length=5, null=True, blank=True)
    taxaIlum = models.FloatField("Tx iluminação Pública", max_length=5)
    corredor = models.FloatField("Iluminação dos Corredores", max_length=5)
    def __str__(self):
        return f"Valor Total: R$  {self.conta:.2f} Taxa Iluminação: R$ {self.taxaIlum:.2f} Corredor: R$: {self.corredor:.2f}"

class Leitura(models.Model):
    anterior = models.IntegerField(verbose_name='Leitura Anterior')
    atual = models.IntegerField(verbose_name='Leitura Atual')
    data = models.DateTimeField(auto_created=True, auto_now=True)
    banca = models.ForeignKey("Bancas" ,on_delete=models.PROTECT, related_query_name='bancas')
    
    def __str__(self):
        return f"{self.banca.qtd}-Banca: ({self.banca.numero}) - ({self.anterior}-{self.atual}) = [ {self.atual - self.anterior}  Kwh ] R$ {(((self.atual - self.anterior) * 0.75))}- Taxa Iluminação ({self.banca.qtd * 7.50 :.2f})- Area comum ({self.banca.qtd * 8.50}) Total = {((self.atual - self.anterior) * 0.75) + (self.banca.qtd * 7.50) + (self.banca.qtd * 8.50 ):.2f} )"
    class Meta:
        ordering = ['banca']

feira2/models.py
from django.db import models


# Create your models here.

# bancas = [('01', "590/611"),
#         ('02', "591 "),
#         ("03", "592/594"),
#         ("04","593"),
#         ('05', '595'), 
#         ('06','596/605'),
#         ('07', '597'),
#         ('08', '598'),
#         ('09', '599'),
#         ('10', '600'),
#         ('11', '601/603'),
#         ('12', '602'),        
#         ('13', '604'),
#         ('14', '606'),
#         ('15', '607'),
#         ('16', '608'),
#         ('17', '609'),
#         ('18', '612/610/640/641'),
#         ('19', '613/615'),
#         ('20', '614/616'),
#         ('21', '618/637'),
#         ('22', '626/633'),
#         ('23', '628'),
#         ('24', '630'),
#         ('25', '631'),
#         ('26', '632'),
#         ('27', '635'),
#         ('28', '636'),
#         ('29', '638/639'),
#         ('30', '642'),
#         ('31', '643'),
#         ('32', '644'),
#         ('33', '645'),
#         ('34', '646'),
# ]



# class Leitura2(models.Model):
#     anterior = models.IntegerField("Leitura anterior")
#     atual = models.IntegerField("Leitura atualr")
#     data = models.DateTimeField(auto_created=True, auto_now=True)
#     banca = models.ForeignKey(Banca, on_delete=models.CASCADE)
    
#     def __str__(self):
#         return f"{self.banca.qtd}-Banca: ({self.banca}) - ({self.anterior}-{self.atual}) = [ {self.atual - self.anterior}  Kwh ] R$ {(((self.atual - self.anterior)* 0.75)/2) + (self.banca.qtd * 7.851) + (self.banca.qtd * 7.901):.2f} "
    


feira2/views.py
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from feira.models import  Leitura, Bancas
from django.urls import reverse_lazy
# controle de login
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ControleView(ListView):
    model = Leitura
    queryset = Leitura.objects.all()
    template_name = 'feira/Controle.html'

class Leitura2View(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Leitura
    queryset = Leitura.objects.all()
    template_name = 'feira2/Leitura_lista.html' 
    

class Leitura2Update(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Leitura
    queryset = Leitura.objects.all()
    fields = ["banca", "anterior", "atual"]
    template_name = 'feira2/Leitura_update.html'
    success_url = reverse_lazy('leitura-lista')
    def form_valid(self, form):       
        url = super().form_valid(form)
        self.object.anterior = self.object.atual
        self.object.atual += 0
        self.object.save()        
        return url
    

    



feira2/templates/feira2/Controle.html
{% extends 'feira2/modelo.html' %}
{% load static %}
{% block titulo %}

{% endblock %}
{% block conteudo %}
<div class="container col-6 auto">
<table class="table table-striped text-center ">    
    <thead>
      <tr>
        <th >Qtd</th>
        <th >Banca</th>
        <th >Leitura anterior (Kw/h) </th>
        <th >Leitura atual (Kw/h) </th>
        <!-- <th >Data da Leitura</th> -->
        <!-- <th >Consumo em Kw/h</th>
        <th >Total a pagar</th>
        <th >Editar </th> -->
      </tr>
    </thead>
    {% for item in object_list %}
    <tbody >      
      <tr > 
        <td class="qtd">{{ item.banca.qtd }}</td>       
        <td>{{ item.banca.numero }}</td>
        <td class="ant">{{ item.atual }}</td>        
        <td class="atual"><input type="text" name="atualizar" id=""></td>
        <!-- <td class="atual"><input type="text" name="data" id=""></td>
        <td class="total"></td> -->
      </tr>      
    </tbody>
    {% endfor %}    
</table>
</div>  
{% endblock %}

feira2/templates/feira2/Leitura_lista.html
{% extends 'feira2/modelo.html' %}
{% block titulo %}
<div class="container">
<nav class="navbar navbar-dark bg-info">
  <div class="container  ">
    <a class="navbar-brand" href="#">
      <!-- <img src="/docs/5.2/assets/brand/bootstrap-logo.svg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top"> -->
      Controle de Energia Feira do Guara
    </a>
  </div>
</nav>
</div>

{% endblock %}
{% block conteudo %}
<div class="container">
<table class="table table-striped text-center">    
    <thead>
      <tr>
        <th >Qtd</th>
        <th >Banca</th>
        <th >Leitura anterior (Kw/h) </th>
        <th >Leitura atual (Kw/h) </th>
        <th >Data da Leitura</th>
        <!-- <th >Consumo em Kw/h</th>
        <th >Total a pagar</th>
        <th >Editar </th> -->
      </tr>
    </thead>
    {% for item in object_list %}
    <tbody >      
      <tr > 
        <td class="qtd">{{ item.banca.qtd }}</td>       
        <td>{{ item.banca.numero }}</td>
        <td class="ant">{{ item.anterior }}</td>        
        <td class="atual">{{ item.atual }}</td>
        <td class="soma"></td>
        <td class="total"></td>
      </tr>      
    </tbody>
    {% endfor %}
    
</table>

</div>  
{% endblock %}

feira2/templates/feira2/Leitura_update.html
{% extends 'feira2/modelo.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  <script src="{% static "js/jquery-3.6.1.min.js" %}"></script>
{% endblock %}
<!-- Bloco conteudo -->
{% block conteudo %}
    <div class="container col-6 auto ">
        <nav class="navbar bg-light">
            <div class="container-fluid">
              <a class="navbar-brand">Controle de Energia Feira do Guará</a>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </nav>
        <div class="container" id="atualizar">
            <form  method="post">
                {% csrf_token %}                
                    {{ form | crispy }}
                <input type="submit" class="btn btn-success" value="confirmar">
            </form>
        </div>
    </div>
{% endblock %}
<!-- Scripts -->
{% block scripts %}
<script id="update" src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script>  
  $("#id_atual").click(function(){
      $("#id_anterior").val($("#id_atual").val())
  })
</script>
{% endblock %}

feira2/templates/feira2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

feira2/templates/feira2/modelo.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}
    <title>Document</title>
    {% endblock %}
</head>
 <body>
    {% if request.user.is_authenticated %}
  <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'listar_leitura' %}" class="nav-link px-2 text-secondary">Leituras</a></li>
          <li><a href="{% url 'controle' %}" class="nav-link px-2 text-white">Controle</a></li>
          <li><a href="{% url 'listar_banca' %}" class="nav-link px-2 text-white">Bancas</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">{{ request.user | title }}</button>
          <a href="{% url 'logout' %}" class="btn btn-warning">Sign-up</a>
        </div>
      </div>
    </div>
  </header>
  {% endif %}
    
    <!-- Bloco Titulo -->
    {% block titulo %}
    
    {% endblock %}
    <!-- Bloco conteudo -->
    {% block conteudo %}

    {% endblock %}
    <!-- Scripts -->
    {% block scripts %} 
        <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>        
    {% endblock %}
</body>
</html>

feira2/templates/feira2/tabela.html
{% extends 'feira2/modelo.html' %}
{% load static %}

{% block conteudo %}
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">Leitura de Energia da feira do Guara</h5>
            <p></p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div id="example_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <div class="dt-buttons ">          
                                <!-- <button class="btn btn-outline-light buttons-copy buttons-html5" tabindex="0" aria-controls="example" type="button"><span>Copy</span></button>  -->
                                <!-- <button class="btn btn-outline-light buttons-excel buttons-html5" tabindex="0" aria-controls="example" type="button"><span>Excel</span></button>  -->
                                <div class="col-sm-4 col-md-6" ><div id="example_filter" class="dataTables_filter text-left"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="example"></label>
                                <button id="pdf" class="btn btn-outline-success  pdf" tabindex="0" aria-controls="example " ><span >PDF</span></button> 
                                <!-- <button class="btn btn-outline-light buttons-print" tabindex="0" aria-controls="example" type="button"><span>Print</span></button> -->
                                <!-- <button type="Application/pdf" class="btn-outline-light buttons-pdf buttons-html5">pdf_</button> -->

                                <!-- <button class="btn btn-outline-light buttons-collection dropdown-toggle buttons-colvis" tabindex="0" aria-controls="example" type="button" aria-haspopup="true"><span>Column visibility</span></button>  -->
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="row container center">
                    <div class="col-sm-9 auto">
                    <table id="examplo" class="table table-striped table-bordered second dataTable " style="width: 100%;" role="grid" aria-describedby="example_info">
                        
                    <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending"  style="width: 33.0089px;">Qtd</th>
                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 53.0089px;">Banca</th>
                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 41.0089px;">Leitura Anterior</th>
                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 26.0089px;">Leitura Atual</th><th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 49.0089px;">Consumo em Kw/h</th>
                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 41.0089px;">Total a pagar</th>
                            <th class="sorting" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 41.0089px;">Checar</th>
                            
                        </thead>
                    <tbody>
                        {% for item in object_list %}            
                    <tr role="row" class="odd text-center">
                            <td class="sorting_1 qtd" >{{ item.banca.qtd }}</td> 
                            <td class="">{{ item.banca.numero }}</td>                           
                            <td class="ant">{{ item.anterior }}</td>
                            <td class="atual">{{ item.atual }}</td>
                            <td class="soma">soma </td> 
                            <td class="total">total </td>
                            <td ><input type="checkbox" name="confirmar" class="Checar"></td>                                             
                        {% endfor %}
                                
                    
                    </tr></tbody>
                    <!-- <p>Total: <span id="somatoria"></span></p>
                    <tfoot>
                        <tr><th rowspan="1" colspan="1">Banca</th><th rowspan="1" colspan="1">Leitra anterior</th><th rowspan="1" colspan="1">Leitura atual</th><th rowspan="1" colspan="1">data da leitura </th>
                    </tfoot> -->
                </table>
            <!-- </div></div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="example_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="example_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="example_previous"><a href="#" aria-controls="example" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="example" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="example_next"><a href="#" aria-controls="example" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li></ul></div></div></div></div> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static '/js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script scr="{% static 'js/printThis.js' %}"></script>
<script src="{% static '/assets/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static '/assets/vendor/slimscroll/jquery.slimscroll.js' %}"></script>
<script src="{% static '/assets/libs/js/main-js.js' %}"></script>


<script>
    $("#pdf").click(()=>{
        // alert('fui clicado')
        window.print();
            
        });

    $('.Checar').click(function(){
        // alert('clicou');
        $(this).toggleClass(".pagou");
               
    });

    
// ############################################
    var lista = $('.soma');
    var ant = $('.ant');
    var atual = $('.atual');
    var total = $('.total')
    var qtd = $('.qtd')
    for (i = 0; i <= lista.length; i ++){
        var soma = atual[i].textContent - ant[i].textContent 
        var txilu = qtd[i].textContent * 7.85 
        var txcom = qtd[i].textContent * 8.41             
        $(lista[i]).html( soma);
        $(total[i]).html("R$ " + (((soma * 0.75)) + txcom + txilu).toFixed(2));        
                        
    } ;
// ############### Imprime PDF #############################
    $("#pdf").click(()=>{
        alert("fui clicado!");
    });

    

                       
</script>
<script>
    
</script>
{% endblock %}